### ISSUE TITLE
package-lock ??

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/analysis#20]
@targos Is there a reason we have a package-lock in this library ?

Or I may add .npmrc to avoid this.

**Comment by targos** [comment]
I think I added it in https://github.com/cheminfo/analysis/commit/6f5161f8c9fd51845e82b975229398a3b6c1211c because of issues with non-major dependency updates.

**Comment by targos** [comment]
Yeah, see https://github.com/cheminfo/analysis/pull/11#issuecomment-1025781231

If you are able to make it work locally and on github actions without the lockfile, it can be removed.
