### ISSUE TITLE
Missing /lib/index.js file on instalation

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/analysis#8]
I was installing iv-analysis on a project and there's no `lib` folder with js files, is this intentional?

**Comment by targos** [comment]
Please don't assign me to issues. I use assignment to know what I am working on.

**Comment by maasencioh** [comment]
Sorry, didn't know

**Comment by targos** [comment]
Tentative fix: https://github.com/cheminfo/analysis/pull/11

**Comment by targos** [comment]
Fixed in v0.1.1: https://unpkg.com/browse/iv-analysis@0.1.1/lib/
